//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "DmitriNesteruk.AsyncDsl.AsyncDslDiagram")]

namespace DmitriNesteruk.AsyncDsl
{
	/// <summary>
	/// DomainClass AsyncDslDiagram
	/// Description for DmitriNesteruk.AsyncDsl.AsyncDslDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("DmitriNesteruk.AsyncDsl.AsyncDslDiagram.DisplayName", typeof(global::DmitriNesteruk.AsyncDsl.AsyncDslDomainModel), "DmitriNesteruk.AsyncDsl.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("DmitriNesteruk.AsyncDsl.AsyncDslDiagram.Description", typeof(global::DmitriNesteruk.AsyncDsl.AsyncDslDomainModel), "DmitriNesteruk.AsyncDsl.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::DmitriNesteruk.AsyncDsl.AsyncDslDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("79453052-ce44-4a83-b1ac-cbb5084926ee")]
	public partial class AsyncDslDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::DmitriNesteruk.AsyncDsl.AsyncDslToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Swimlane support
		
		/// <summary>
		/// Gets whether or not swimlanes are supported in this Diagram.
		/// </summary>
		public override bool HasSwimlanes
		{
			get { return true; }
		}
		
		/// <summary>
		/// Initializes the starting swimlanes in a new Diagram.
		/// </summary>
		/// <remarks>
		/// This method is not called during successful deserialization, only when either a blank diagram is created or diagram deserialization fails and a diagram is created to make things work.
		/// 
		/// This method does not create shapes for swimlanes with shape maps specified in the DSL definition, only those swimlanes which are not mapped.
		/// The assumption here is that if a swimlane is mapped to a domain class, then an instance of that class  will be created when the element mapped to the diagram is created,
		/// and swimlane shapes will be created as part of view fixup.
		/// </remarks>
		internal virtual void InitializeSwimlanes()
		{
		}
		
		/// <summary>
		/// Gets a collection of domain classes which are mapped to swimlane shapes.
		/// </summary>
		public override sealed global::System.Collections.Generic.IEnumerable<DslModeling::DomainClassInfo> CreatableSwimLaneSubjects
		{
			get
			{
				yield return this.Store.DomainDataDirectory.GetDomainClass(typeof(global::DmitriNesteruk.AsyncDsl.Process));
			}
		}
		
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::DmitriNesteruk.AsyncDsl.Finish)
			{
				global::DmitriNesteruk.AsyncDsl.FinishShape newShape = new global::DmitriNesteruk.AsyncDsl.FinishShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.Operation)
			{
				global::DmitriNesteruk.AsyncDsl.OperationShape newShape = new global::DmitriNesteruk.AsyncDsl.OperationShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.Start)
			{
				global::DmitriNesteruk.AsyncDsl.StartShape newShape = new global::DmitriNesteruk.AsyncDsl.StartShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.Process)
			{
				global::DmitriNesteruk.AsyncDsl.ThreadSwimLane newShape = new global::DmitriNesteruk.AsyncDsl.ThreadSwimLane(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.Comment)
			{
				global::DmitriNesteruk.AsyncDsl.CommentShape newShape = new global::DmitriNesteruk.AsyncDsl.CommentShape(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.OperationReferencesComments)
			{
				global::DmitriNesteruk.AsyncDsl.CommentConnector newShape = new global::DmitriNesteruk.AsyncDsl.CommentConnector(this.Partition);
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.FlowElementBlocks)
			{
				global::DmitriNesteruk.AsyncDsl.FinishToStartConnector newShape = new global::DmitriNesteruk.AsyncDsl.FinishToStartConnector(this.Partition);
				return newShape;
			}
			if(element is global::DmitriNesteruk.AsyncDsl.FlowElementContinuations)
			{
				global::DmitriNesteruk.AsyncDsl.StartToStartConnector newShape = new global::DmitriNesteruk.AsyncDsl.StartToStartConnector(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::DmitriNesteruk.AsyncDsl.ThreadSwimLane.DecoratorsInitialized += ThreadSwimLaneDecoratorMap.OnDecoratorsInitialized;
			global::DmitriNesteruk.AsyncDsl.OperationShape.DecoratorsInitialized += OperationShapeDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ThreadSwimLane.
		/// </summary>
		internal static partial class ThreadSwimLaneDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ThreadSwimLane.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DmitriNesteruk.AsyncDsl.Process.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for OperationShape.
		/// </summary>
		internal static partial class OperationShapeDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for OperationShape.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DmitriNesteruk.AsyncDsl.Operation.NameDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NameDecorator").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::DmitriNesteruk.AsyncDsl.FinishToStartConnectorConnectAction finishToStartConnectorConnectAction;
		private global::DmitriNesteruk.AsyncDsl.CommentConnectionConnectAction commentConnectionConnectAction;
		private global::DmitriNesteruk.AsyncDsl.StartToStartConnectorConnectAction startToStartConnectorConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::DmitriNesteruk.AsyncDsl.AsyncDslToolboxHelper.FinishToStartConnectorFilterString))
				{
					if (this.finishToStartConnectorConnectAction == null)
					{
						this.finishToStartConnectorConnectAction = new global::DmitriNesteruk.AsyncDsl.FinishToStartConnectorConnectAction(this);
						this.finishToStartConnectorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.finishToStartConnectorConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DmitriNesteruk.AsyncDsl.AsyncDslToolboxHelper.CommentConnectionFilterString))
				{
					if (this.commentConnectionConnectAction == null)
					{
						this.commentConnectionConnectAction = new global::DmitriNesteruk.AsyncDsl.CommentConnectionConnectAction(this);
						this.commentConnectionConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.commentConnectionConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DmitriNesteruk.AsyncDsl.AsyncDslToolboxHelper.StartToStartConnectorFilterString))
				{
					if (this.startToStartConnectorConnectAction == null)
					{
						this.startToStartConnectorConnectAction = new global::DmitriNesteruk.AsyncDsl.StartToStartConnectorConnectAction(this);
						this.startToStartConnectorConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.startToStartConnectorConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.finishToStartConnectorConnectAction != null)
					{
						this.finishToStartConnectorConnectAction.Dispose();
						this.finishToStartConnectorConnectAction = null;
					}
					if(this.commentConnectionConnectAction != null)
					{
						this.commentConnectionConnectAction.Dispose();
						this.commentConnectionConnectAction = null;
					}
					if(this.startToStartConnectorConnectAction != null)
					{
						this.startToStartConnectorConnectAction.Dispose();
						this.startToStartConnectorConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// AsyncDslDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x79453052, 0xce44, 0x4a83, 0xb1, 0xac, 0xcb, 0xb5, 0x08, 0x49, 0x26, 0xee);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AsyncDslDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public AsyncDslDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace DmitriNesteruk.AsyncDsl
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.Start), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.Operation), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.Finish), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.FlowElementBlocks), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.FlowElementContinuations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.OperationReferencesComments), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.Process), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.Comment), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::DmitriNesteruk.AsyncDsl.Start)
				{
					parentElement = GetParentForStart((global::DmitriNesteruk.AsyncDsl.Start)childElement);
				} else
				if(childElement is global::DmitriNesteruk.AsyncDsl.Operation)
				{
					parentElement = GetParentForOperation((global::DmitriNesteruk.AsyncDsl.Operation)childElement);
				} else
				if(childElement is global::DmitriNesteruk.AsyncDsl.Finish)
				{
					parentElement = GetParentForFinish((global::DmitriNesteruk.AsyncDsl.Finish)childElement);
				} else
				if(childElement is global::DmitriNesteruk.AsyncDsl.Process)
				{
					parentElement = GetParentForProcess((global::DmitriNesteruk.AsyncDsl.Process)childElement);
				} else
				if(childElement is global::DmitriNesteruk.AsyncDsl.Comment)
				{
					parentElement = GetParentForComment((global::DmitriNesteruk.AsyncDsl.Comment)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::DmitriNesteruk.AsyncDsl.ExampleModel GetParentForProcess( global::DmitriNesteruk.AsyncDsl.Process root )
			{
				// Segments 0 and 1
				global::DmitriNesteruk.AsyncDsl.ExampleModel result = root.ExampleModel;
				if ( result == null ) return null;
				return result;
			}
			public static global::DmitriNesteruk.AsyncDsl.Process GetParentForOperation( global::DmitriNesteruk.AsyncDsl.FlowElement root )
			{
				// Segments 0 and 1
				global::DmitriNesteruk.AsyncDsl.Process result = root.Process;
				if ( result == null ) return null;
				return result;
			}
			public static global::DmitriNesteruk.AsyncDsl.Process GetParentForStart( global::DmitriNesteruk.AsyncDsl.FlowElement root )
			{
				// Segments 0 and 1
				global::DmitriNesteruk.AsyncDsl.Process result = root.Process;
				if ( result == null ) return null;
				return result;
			}
			public static global::DmitriNesteruk.AsyncDsl.Process GetParentForFinish( global::DmitriNesteruk.AsyncDsl.FlowElement root )
			{
				// Segments 0 and 1
				global::DmitriNesteruk.AsyncDsl.Process result = root.Process;
				if ( result == null ) return null;
				return result;
			}
			public static global::DmitriNesteruk.AsyncDsl.ExampleModel GetParentForComment( global::DmitriNesteruk.AsyncDsl.Comment root )
			{
				// Segments 0 and 1
				global::DmitriNesteruk.AsyncDsl.ExampleModel result = root.ExampleModel;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.OperationReferencesComments), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.FlowElementBlocks), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DmitriNesteruk.AsyncDsl.FlowElementContinuations), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::DmitriNesteruk.AsyncDsl.AsyncDslDiagram diagram = linkShape.Diagram as global::DmitriNesteruk.AsyncDsl.AsyncDslDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
