//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmitriNesteruk.AsyncDsl
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "async";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"AsyncDsl";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"DmitriNesteruk";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID AsyncDslDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AsyncDslCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID AsyncDslExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AsyncDslCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewAsyncDslExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(AsyncDslCommandSetId), 0x0001);
	
		// Package identifier
		public const string AsyncDslPackageId = "dbd49cd6-6d2b-4955-bc30-e4b5e7001b28";
		
		// Editor factory identifier
		public const string AsyncDslEditorFactoryId = "98738429-9eb7-479f-af23-a3ccccc9086e";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string AsyncDslModelExplorerToolWindowId = "ed7b1112-3d69-4f6b-accc-196fb7235e2e";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace DmitriNesteruk.AsyncDsl
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string AsyncDslCommandSetId = "9bf522ec-b92a-4c1e-ad87-72cd8bab7cba";
	}
}